services:
  # Keep the upstream Caddy service in the file tree,
  # but disable it for Coolify so it won't bind 80/443 or even start.
  caddy:
    profiles: ["local-caddy"]   # only runs if profile enabled (we WON'T enable it in Coolify)
    ports: []                   # remove host port bindings
    expose:
      - "80"                    # harmless internal port; Coolify won't attach to caddy anyway
    restart: "no"               # don't auto-restart in case someone triggers it

  # Make Ghost reachable by Coolify's reverse proxy internally
  ghost:
    expose:
      - "2368"
